name: 'Build'

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: rdeak/semantic-release-action@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish docker image
        uses: rdeak/publish-image-action@v1
        with:
          release_tag: ${{ env.RELEASE_TAG }}
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws_role_name: ${{ secrets.AWS_ROLE_NAME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_ecr_name: ${{ secrets.AWS_ECR_NAME }}
